<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Gestion des utilisateurs</span></h1>

    <p>
        Congratulations! J'ai reussi a afficher mon premier module
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Skeleton Application</a>.
     Lorem ipsum dolor sit, amet consectetur adipisicing elit.
      Quae magnam, earum sunt ea magni hic a iure illum obcaecati? Maxime quis inventore pariatur officiis suscipit soluta dolores porro est ab!
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Fork Zend Framework on GitHub &raquo;</a></p>
</div>
