<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700|Kalam:400,700" rel="stylesheet">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <?= $this->headTitle('TRAIL')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('description', 'site de sport')
            ->appendName('author', 'Ansonika')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'])

           // $this->headLink(['rel' => 'apple-touch-icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . 'img/apple-touch-icon-57x57-precomposed.png'])
            //$this->headLink(['rel' => 'apple-touch-icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . 'img/apple-touch-icon-72x72-precomposed.png'])
            //$this->headLink(['rel' => 'apple-touch-icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . 'img/apple-touch-icon-114x114-precomposed.png'])
            //$this->headLink(['rel' => 'apple-touch-icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . 'img/apple-touch-icon-114x114-precomposed.png'])
           

            ->prependStylesheet($this->basePath('css/animate.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))            
            ->prependStylesheet($this->basePath('css/menu.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/responsive.min.css'))
            ->prependStylesheet($this->basePath('css/icon_fonts/css/all_icons.min.css'))
            ->prependStylesheet($this->basePath('css/magnific-popup.min.css'))
            
            ->prependStylesheet($this->basePath('css/custom.css'))

        ?>
	
        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/modernizr.js'))
        ?>

    </head>
    <body>
        
            <?= $this->content ?>
        
        <?= $this->inlineScript()
             ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
             ->prependFile($this->basePath('js/common_scripts_min.js'))
             ->prependFile($this->basePath('assets/validate.js')) 
             ->prependFile($this->basePath('js/functions.js'))

            // SPECIFIC SCRIPTS 
             ->prependFile($this->basePath('js/bootstrap-portfilter.min.js'))
             ->prependFile($this->basePath('js/video_header.js'))
         ?>
        <script>
            HeaderVideo.init({
                container: $('.header-video'),
                header: $('.header-video--media'),
                videoTrigger: $("#video-trigger"),
                autoPlayVideo: true
            });
	    </script>
    </body>
</html>
