<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700|Kalam:400,700" rel="stylesheet">
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->


        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <?= $this->headTitle('TRAIL')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('description', 'site de sport')
            ->appendName('author', 'Ansonika')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
            $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'])

            //$this->headLink(['rel' => 'apple-touch-icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/apple-touch-icon-57x57-precomposed.png'])
            //$this->headLink(['rel' => 'apple-touch-icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . 'img/apple-touch-icon-72x72-precomposed.png'])
            //$this->headLink(['rel' => 'apple-touch-icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . 'img/apple-touch-icon-114x114-precomposed.png'])
            //$this->headLink(['rel' => 'apple-touch-icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . 'img/apple-touch-icon-114x114-precomposed.png'])
           

            ->prependStylesheet($this->basePath('css/animate.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))            
            ->prependStylesheet($this->basePath('css/menu.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/responsive.min.css'))
            ->prependStylesheet($this->basePath('css/icon_fonts/css/all_icons.min.css'))
            ->prependStylesheet($this->basePath('css/magnific-popup.min.css'))
            
            ->prependStylesheet($this->basePath('css/custom.css'))

        ?>
	
        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/modernizr.js'))
        ?>

    </head>
    <body>
        
<!-- Header ================================================== -->
<style>
    .a{
        text-decoration:none;
        color: #fff;
    }
</style>
<header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-3">
                <a href="http://localhost:81" id="logo" class="a">
                    <h1 style="font-family: Poppins,Arial,sans-serif;">TRAIL</h1>
                    <!-- <img src="img/logo.png" width="95" height="27" alt="" data-retina="true" class="logo_normal">
                    <img src="img/logo_sticky.png" width="95" height="27" alt="" data-retina="true" class="logo_sticky"> -->
                </a>
            </div>
            <nav class="col-xs-9">
                <ul id="access_top">
                    <li><a href="#" class="search-overlay-menu-btn"><i class="icon-search-6"></i></a>
                    </li>
                    <li><a href="#" data-toggle="modal" data-target="#login" class="hidden-xs">Connexion</a>
                    </li>
                    <li><a href="#" data-toggle="modal" data-target="#register" class="hidden-xs">Inscription</a>
                    </li>
                    <!-- <li><a href="<?php //$this->url('Inscription',['action'=>"incription"])?>" class="hidden-xs">Inscription</a>
                    </li> -->
                </ul>
                <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
                <div class="main-menu">
                    <div id="header_menu">
                        <!-- <img src="img/logo.png" width="95" height="27" alt="Lovefit" data-retina="true"> -->
                        <h1 style="font-family: Poppins,Arial,sans-serif;">TRAIL</h1>
                    </div>
                    <a href="#" class="open_close" id="close_in"><i class="icon_close"></i></a>
                    <ul>
                        <li class="submenu">
                            <a href="javascript:void(0);" class="show-submenu">Course<i class="icon-down-open-mini"></i></a>
                            <ul>
                                <!-- <li><a href="#0">Home versions</a>
                                     <ul>
                                        <li><a href="index.html">Home Video Bg</a>
                                        </li>
                                        <li><a href="index_2.html">Home Layer Slider</a>
                                        </li>
                                        <li><a href="index_3.html">Home Cookie Bar</a>
                                        </li>
                                        <li><a href="index_4.html">Home Pop Up</a>
                                        </li>
                                    </ul> 
                                </li> -->
                                <li><a href="fitness-course-1.html">Ultra trail des deux côtes 106km</a>
                                </li>
                                <li><a href="fitness-course-2.html">Trail des 3 lacs 50km</a>
                                </li>
                                <li><a href="about.html">Marche 35km</a>
                                </li>
                                <!-- <li><a href="subscribe-working.html">Subscribe working</a>
                                </li> -->
                                <li><a href="<?= $this->url('ResultatCourse',['action'=>"resultat"])?>">Résultats</a></li>
                                    <!-- <ul>
                                        <li><a href="cart-page-1.html">Cart section 1</a>
                                        </li>
                                        <li><a href="cart-page-2.html">Cart section 2</a>
                                        </li>
                                        <li><a href="cart-page-3.html">Cart section 3</a>
                                        </li>
                                    </ul> -->
                                <!-- </li> -->

                            </ul>
                        </li>
                        <li><a href="#0">Partenaires</a>
                        </li>
                        <li class="submenu"><a href="javascript:void(0);" class="show-submenu">Informations Pratiques<i class="icon-down-open-mini"></i></a>
                            <ul>
                                <li><a href="blog.html">Infos Sénégal</a>
                                </li>
                                <li><a href="faq.html">FAQ</a>
                                </li>
                            </ul>
                        </li>
                        <li><a href="<?= $this->url('ListeParticipant',['action'=>"listeparticipant"])?>">Liste des participants</a>
                        </li>   
                        <li><a href="contacts.html">Contacts</a>
                        </li>
                        <li><a href="#" data-toggle="modal" data-target="#register" class="visible-xs">Inscription</a>
                        </li>
                        <!-- <li><a href="<?php//= $this->url('Inscription',['action'=>"incription"])?>" class="visible-xs">Inscription</a>
                        </li> -->
                        <li><a href="#" data-toggle="modal" data-target="#login" class="visible-xs">Connexion</a>
                        </li>

                    </ul>
                </div>
                <!-- End main-menu -->
            </nav>
        </div>
        <!-- End row -->
    </div>
    <!-- End container -->
</header>
<!-- End Header =============================================== -->
            <?= $this->content ?>
        
        <?= $this->inlineScript()
             ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
             ->prependFile($this->basePath('js/common_scripts_min.js'))
             ->prependFile($this->basePath('assets/validate.js')) 
             ->prependFile($this->basePath('js/functions.js'))

            // SPECIFIC SCRIPTS 
             ->prependFile($this->basePath('js/bootstrap-portfilter.min.js'))
             ->prependFile($this->basePath('js/video_header.js'))
         ?>
        <script>
            HeaderVideo.init({
                container: $('.header-video'),
                header: $('.header-video--media'),
                videoTrigger: $("#video-trigger"),
                autoPlayVideo: true
            });
	    </script>
    </body>
</html>
