    
    <section class="parallax_window_in" data-parallax="scroll" data-image-src="/img/sub_header_general.jpg" data-natural-width="1400" data-natural-height="470">
      
		<div id="sub_content_in">
			<h1>Contacts</h1>
			<p>"Usu habeo equidem sanctus no ex melius labitur conceptam eos"</p>
		</div>
	</section>
    <nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand"></a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Rechercher" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Rechercher</button>
    </form>
  </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col mt-3">
          
        

        </div>
    </div>
</div>