

<div class="layer"></div>
<!-- Mobile menu overlay mask -->

<!-- <div id="preloader">
    <div data-loader="circle-side"></div>
</div> -->
<!-- End Preload -->


<!-- SubHeader =============================================== -->
<section class="header-video">
    <div id="hero_video">
        <div id="sub_content">
            <div class="mobile_fix">
                <h1>Video <strong>Remise</strong> en Forme</h1>
                <p>
                    Tombez amoureux de votre physique
                </p>
            </div>
        </div>
        <!-- End sub_content -->
    </div>
    <img src="img/video_fix.png" alt="" class="header-video--media" data-video-src="video/intro" data-teaser-source="video/intro" data-provider="" data-video-width="1920" data-video-height="960">
    <div id="count" class="hidden-xs">
        <ul>
            <li><span class="number">653</span> Entrainement</li>
            <li><span class="number">1246</span> Personnes desservies</li>
            <li><span class="number">2343</span> Utilisateurs enregistrés</li>
        </ul>
    </div>
</section>
<!-- End Header video -->
<!-- End SubHeader ============================================ -->

<section id="feat">
    <div class="container">
        <h2 class="main_title"><em></em>Comment fonctionne TRAIL<span>Tombez amoureux de votre physique</span></h2>
        <p class="lead styled">
            Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie. Sed ad debet scaevola, ne mel lorem legendos.
        </p>
        <div class="row">
            <div class="col-sm-4 wow fadeIn animated" data-wow-delay="0.2s">
                <div class="box_feat" id="icon_2">
                    <h3>Videos d'Entrainement</h3>
                    <p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie. Sed ad debet scaevola, ne mel lorem legendos. </p>
                </div>
            </div>
            <div class="col-sm-4 wow fadeIn animated" data-wow-delay="0.5s">
                <div class="box_feat" id="icon_1">
                    <h3>Formateur Expert</h3>
                    <p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie. Sed ad debet scaevola, ne mel lorem legendos. </p>
                </div>
            </div>
            <div class="col-sm-4 wow fadeIn animated" data-wow-delay="1s">
                <div class="box_feat" id="icon_3">
                    <h3>Jouez partout</h3>
                    <p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie. Sed ad debet scaevola, ne mel lorem legendos. </p>
                </div>
            </div>
        </div>
        <!-- End row -->
    </div>
    <!-- End container -->
</section>
<!-- End section -->
<div class="container_styled_1">
    <div class="container margin_60_35">
        <h2 class="main_title"><em></em>Dernères Videos d'entrainement<span>Fall in love with Fitness</span></h2>
        <div id="filter_buttons">
            <button data-toggle="portfilter" class="active" data-target="all">All</button>
            <button data-toggle="portfilter" data-target="Yoga">Yoga</button>
            <button data-toggle="portfilter" data-target="Strength">Strength</button>
            <button data-toggle="portfilter" data-target="Cardio">Cardio</button>
            <button data-toggle="portfilter" data-target="Pilates">Pilates</button>
        </div>
        <div class="row">
            <div class="col-md-4" data-tag="Yoga">
                <div class="course_container">
                    <div class="ribbon top"><span>Top Sell</span>
                    </div>
                    <figure>
                        <a href="fitness-course-1.html">
                            <img src="img/course_1.jpg" width="800" height="533" class="img-responsive" alt="Image">
                            <div class="short_info"><i class="icon-clock-1"></i>2 hr 56 min</div>
                        </a>
                    </figure>
                    <div class="course_title">
                        <div class="type"><span>Yoga</span>
                        </div>
                        <h3><a href="fitness-course-1.html">Yoga Fundamentals</a></h3>
                        <div class="info_2 clearfix"><span class="price">39.90<sup>$</sup></span><span class="users">450</span>
                        </div>
                    </div>
                </div>
                <!-- End box course_container -->
            </div>
            <div class="col-md-4" data-tag="Yoga">
                <div class="course_container">
                    <div class="ribbon top"><span>Top sell</span>
                    </div>
                    <figure>
                        <a href="fitness-course-1.html">
                            <img src="img/course_2.jpg" width="800" height="533" class="img-responsive" alt="Image">
                            <div class="short_info"><i class="icon-clock-1"></i>2 hr 56 min</div>
                        </a>
                    </figure>
                    <div class="course_title">
                        <div class="type"><span>Yoga</span>
                        </div>
                        <h3><a href="fitness-course-1.html">Total Body Stretching </a></h3>
                        <div class="info_2 clearfix"><span class="price">39.90<sup>$</sup></span><span class="users">450</span>
                        </div>
                    </div>
                </div>
                <!-- End box course_container -->
            </div>
            <div class="col-md-4" data-tag="Yoga">
                <div class="course_container">
                    <div class="ribbon"><span>Popular</span>
                    </div>
                    <figure>
                        <a href="fitness-course-1.html">
                            <img src="img/course_3.jpg" width="800" height="533" class="img-responsive" alt="Image">
                            <div class="short_info"><i class="icon-clock-1"></i>2 hr 56 min</div>
                        </a>
                    </figure>
                    <div class="course_title">
                        <div class="type"><span>Yoga</span>
                        </div>
                        <h3><a href="fitness-course-1.html">Flexibility and Toning</a></h3>
                        <div class="info_2 clearfix"><span class="price">39.90<sup>$</sup></span><span class="users">450</span>
                        </div>
                    </div>
                </div>
                <!-- End box course_container -->
            </div>
            <div class="col-md-4" data-tag="Strength">
                <div class="course_container">
                    <div class="ribbon"><span>Popular</span>
                    </div>
                    <figure>
                        <a href="fitness-course-1.html">
                            <img src="img/course_4.jpg" width="800" height="533" class="img-responsive" alt="Image">
                            <div class="short_info"><i class="icon-clock-1"></i>2 hr 56 min</div>
                        </a>
                    </figure>
                    <div class="course_title">
                        <div class="type"><span>Strength</span>
                        </div>
                        <h3><a href="fitness-course-1.html">Strength Upper Body</a></h3>
                        <div class="info_2 clearfix"><span class="price">39.90<sup>$</sup></span><span class="users">450</span>
                        </div>
                    </div>
                </div>
                <!-- End box course_container -->
            </div>

            <div class="col-md-4" data-tag="Strength">
                <div class="course_container">
                    <div class="ribbon"><span>Popular</span>
                    </div>
                    <figure>
                        <a href="#0">
                            <img src="img/course_5.jpg" width="800" height="533" class="img-responsive" alt="Image">
                            <div class="short_info"><i class="icon-clock-1"></i>2 hr 56 min</div>
                        </a>
                    </figure>
                    <div class="course_title">
                        <div class="type"><span>Strength</span>
                        </div>
                        <h3><a href="#0">Fat Burning Butt and Thigh </a></h3>
                        <div class="info_2 clearfix"><span class="price">39.90<sup>$</sup></span><span class="users">450</span>
                        </div>
                    </div>
                </div>
                <!-- End box course_container -->
            </div>
            <div class="col-md-4" data-tag="Cardio">
                <div class="course_container">
                    <div class="ribbon"><span>Popular</span>
                    </div>
                    <figure>
                        <a href="fitness-course-1.html">
                            <img src="img/course_6.jpg" width="800" height="533" class="img-responsive" alt="Image">
                            <div class="short_info"><i class="icon-clock-1"></i>2 hr 56 min</div>
                        </a>
                    </figure>
                    <div class="course_title">
                        <div class="type"><span>Cardio</span>
                        </div>
                        <h3><a href="fitness-course-1.html">1000 Calorie Workout Video</a></h3>
                        <div class="info_2 clearfix"><span class="price">39.90<sup>$</sup></span><span class="users">450</span>
                        </div>
                    </div>
                </div>
                <!-- End box course_container -->
            </div>
            <div class="col-md-4" data-tag="Cardio">
                <div class="course_container">
                    <figure>
                        <a href="fitness-course-1.html">
                            <img src="img/course_7.jpg" width="800" height="533" class="img-responsive" alt="Image">
                            <div class="short_info"><i class="icon-clock-1"></i>2 hr 56 min</div>
                        </a>
                    </figure>
                    <div class="course_title">
                        <div class="type"><span>Cardio</span>
                        </div>
                        <h3><a href="fitness-course-1.html">Fat Burning Cardio</a></h3>
                        <div class="info_2 clearfix"><span class="price">39.90<sup>$</sup></span><span class="users">450</span>
                        </div>
                    </div>
                </div>
                <!-- End box course_container -->
            </div>
            <div class="col-md-4" data-tag="Pilates">
                <div class="course_container">
                    <figure>
                        <a href="fitness-course-1.html">
                            <img src="img/course_8.jpg" width="800" height="533" class="img-responsive" alt="Image">
                            <div class="short_info"><i class="icon-clock-1"></i>2 hr 56 min</div>
                        </a>
                    </figure>
                    <div class="course_title">
                        <div class="type"><span>Pilates</span>
                        </div>
                        <h3><a href="fitness-course-1.html">Lower Body Pilates</a></h3>
                        <div class="info_2 clearfix"><span class="price">39.90<sup>$</sup></span><span class="users">450</span>
                        </div>
                    </div>
                </div>
                <!-- End box course_container -->
            </div>
            <div class="col-md-4">
                <a href="explore-1.html" id="view_all"><span><i class="arrow_carrot-right_alt2"></i>View all courses</span></a>
            </div>
        </div>
        <!-- End row -->
    </div>
    <!-- End container -->
</div>
<!-- End container_styled_1 -->

<section class="margin_60_35" id="testimonials">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3>Available on all Devices</h3>
                <p class="lead">Lorem ipsum dolor sit amet, dolore deleniti appareat per no. In ius aliquam suavitate repudiare, pro an quidam inimicus, duo liber labitur repudiandae in.</p>
                <p>
                    <p>Lorem ipsum dolor sit amet, dolore deleniti appareat per no. In ius aliquam suavitate repudiare, pro an quidam inimicus, duo liber labitur repudiandae in. Nec no tamquam delenit, sit equidem ornatus accommodare at, pro graeco debitis deterruisset no. Eam at veri oratio principes, sit ad vero ipsum affert.</p>
                    <div id="compatib">
                        Compatible with Android/IOS
                    </div>
            </div>
            <div class="col-md-6">
                <img src="img/devices.png" width="600" height="355" alt="" class="img-responsive">
            </div>
        </div>
        <!--  End row -->
    </div>
    <!--  End container-->
</section>
<!--  End section-->

<section class="promo_full">
    <div class="promo_full_wp">
        <div>
            <h3>Ce que nos clients pensent de nous<span>Id tale utinam ius, an mei omnium recusabo iracundia.</span></h3>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="carousel_testimonials">
                            <div>
                                <div class="box_overlay">
                                    <div class="pic">
                                        <figure><img src="img/testimonial_1.jpg" alt="" class="img-circle">
                                        </figure>
                                        <h4>Roberta<small>12 October 2015</small></h4>
                                    </div>
                                    <div class="comment">
                                        "Mea ad postea meliore fuisset. Timeam repudiare id eum, ex paulo dictas elaboraret sed, mel cu unum nostrud."
                                    </div>
                                </div>
                                <!-- End box_overlay -->
                            </div>

                            <div>
                                <div class="box_overlay">
                                    <div class="pic">
                                        <figure><img src="img/testimonial_1.jpg" alt="" class="img-circle">
                                        </figure>
                                        <h4>Roberta<small>12 October 2015</small></h4>
                                    </div>
                                    <div class="comment">
                                        "No nam indoctum accommodare, vix ei discere civibus philosophia. Vis ea dicant diceret ocurreret."
                                    </div>
                                </div>
                                <!-- End box_overlay -->
                            </div>

                            <div>
                                <div class="box_overlay">
                                    <div class="pic">
                                        <figure><img src="img/testimonial_1.jpg" alt="" class="img-circle">
                                        </figure>
                                        <h4>Roberta<small>12 October 2015</small></h4>
                                    </div>
                                    <div class="comment">
                                        "No nam indoctum accommodare, vix ei discere civibus philosophia. Vis ea dicant diceret ocurreret."
                                    </div>
                                </div>
                                <!-- End box_overlay -->
                            </div>

                        </div>
                        <!-- End carousel_testimonials -->
                    </div>
                    <!-- End col-md-8 -->
                </div>
                <!-- End row -->
            </div>
            <!-- End container -->
        </div>
        <!-- End promo_full_wp -->
    </div>
    <!-- End promo_full -->
</section>
<!-- End section -->

<div id="newsletter_container">
    <div class="container margin_60">
        <div class="row">
            <div class="col-md-10 col-md-offset-1 text-center">
                <h3>Inscrivez-vous à nos communications pour recevoir nos meilleures offres!.</h3>
                <div id="message-newsletter"></div>
                <form method="post" action="assets/newsletter.php" name="newsletter" id="newsletter" class="form-inline">
                    <input name="email_newsletter" id="email_newsletter" type="email" value="" placeholder="Votre mail" class="form-control">
                    <button id="submit-newsletter" class="btn_1">S'inscrire</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End newsletter_container -->

<footer>
    <div class="container">
        <div class="row ">
            <div class="col-md-3 col-sm-12">
                <p>
                    <!-- <img src="img/logo.png" width="95" height="27" alt="Lovefit" data-retina="true"> -->
                    <h3 style="font-family: Poppins,Arial,sans-serif;color:#fff">Trail</h3>
                </p>
                <div id="social">
                    <ul>
                        <li><a href="#"><i class="icon-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="icon-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="icon-google"></i></a>
                        </li>
                        <li><a href="#"><i class="icon-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <h4>Information</h4>
                <ul>
                    <li><a href="#">Information</a>
                    </li>
                    <li><a href="#">Partenaires</a>
                    </li>
                    <li><a href="#">Connexion</a>
                    </li>
                    <li><a href="#">Inscription</a>
                    </li>
                    <li><a href="#">Contact</a>
                    </li>
                    <li><a href="#">FAQ</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6">
                <h4>COURSE</h4>
                <ul>
                    <li><a href="#">Ultra trail des deux côtes 106km</a>
                    </li>
                    <li><a href="#">Trail des 3 lacs 50km</a>
                    </li>
                    <li><a href="#">Marche 35km</a>
                    </li>
                    <li><a href="#">Résultats</a>
                    </li>

                </ul>
            </div>
            <div class="col-md-3 hidden-sm hidden-xs">
                <img src="img/footer_img.png" width="257" height="302" alt="Image" class="footer_pic">
            </div>
        </div>
        <!-- End row -->
    </div>
    <!-- End container -->
</footer>
<!-- End footer -->
<div id="copy">
    <div class="container">
        ©TRAIL 2022 - All rights reserved.
    </div>
</div>
<!-- End copy -->

<div id="toTop"></div>
<!-- Back to top button -->

<!-- Login modal -->
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myLogin" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-popup">
            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
            <label for="">connexion</label>
            <form action="#" class="popup-form" id="myLogin">
                <input type="text" class="form-control" placeholder="Email">
                <input type="text" class="form-control" placeholder="mot de passe">
                <!-- <div class="checkbox-holder text-left">
                    <div class="checkbox">
                        <input type="checkbox" value="accept_1" id="check_1" name="check_1" />
                        <label for="check_1"><span>I Agree to the <strong>Terms &amp; Conditions</strong></span>
                        </label>
                    </div>
                </div> -->
                <button type="submit" class="btn btn-submit border border-info">connexion</button>
            </form>
        </div>
    </div>
</div>

<!-- Register modal -->
 <div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="myRegister" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-popup">
            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
            <h4>Inscription</h4>
            <form action="#" class="popup-form " id="myRegister">
                <div class="row">
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Nom">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Prenom">
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Date de naissance">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Numero de téléphone">
                    </div>
               </div>
                <div class="row">
                    <div class="col">
                        <input type="email" class="form-control" placeholder="Email">
                    </div>
                    <div class="col">
                        <input type="email" class="form-control" placeholder="Email de confirmation">
                    </div>
                </div>
                sexe:
              <div class="form-check form-check-inline">
                <input class="" type="radio" name="" id="" value="">
                <label class="form-check-label" for="">Homme</label>
                </div>
                <div class="form-check form-check-inline">
                <input class="" type="radio" name="" id="" value="">
                <label class="form-check-label" for="">Femme</label>
                </div>

                <div class="row">
                    <div class="col">
                        <div class="form-group">
                                <label for="">Nationalité</label>
                                <select class="form-select" name="" id="">
                                    <option value="" selected>senegalais</option>
                                    <option value="">senegalais</option>
                                    <option value="">senegalais</option>
                                </select>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="">Pays de résidence</label>
                            <select name="" id="" class="form-select">
                                <option value="" selected>SENEGAL</option>
                                <option value="">GAMBIE</option>
                                <option value="">senegalais</option>
                            </select>
                        </div>
                    </div>
                </div>
               

              
                <button type="submit" class="btn btn-submit border border-danger">Enregistrer</button>
            </form>

        </div>
    </div>
</div> 

<!-- Search Menu -->
<div class="search-overlay-menu">
    <span class="search-overlay-close"><i class="icon_close"></i></span>
    <form role="search" id="searchform" method="get">
        <input value="" name="q" type="search" placeholder="Search..." />
        <button type="submit"><i class="icon-search-6"></i>
        </button>
    </form>
</div>
