<h1>Inscription</h1>
<!-- Register modal -->

            <form action="#" class="popup-form " id="myRegister">
                <input type="text" class="form-control" placeholder="Nom">
                <input type="text" class="form-control" placeholder="Prenom">
                <input type="text" class="form-control" placeholder="Date de naissance">
                <input type="email" class="form-control" placeholder="Email">
                <input type="email" class="form-control" placeholder="Email de confirmation">
                <div class="form-group">
                    <label for="">Nationalité</label>
                    <select class="form-select" name="" id="">
                        <option value="" selected>senegalais</option>
                        <option value="">senegalais</option>
                        <option value="">senegalais</option>
                    </select>
                </div>
                <input type="text" class="form-control" placeholder="Numero de téléphone">
                <div class="form-group">
                    <label for="">Pays de résidence</label>
                        <select name="" id="" class="form-select">
                            <option value="" selected>SENEGAL</option>
                            <option value="">GAMBIE</option>
                            <option value="">senegalais</option>
                        </select>
                </div>
                <button type="submit" class="btn btn-submit border border-danger">Enregistrer</button>
            </form>
