    
    <section class="parallax_window_in" data-parallax="scroll" data-image-src="/img/sub_header_general.jpg" data-natural-width="1400" data-natural-height="470">
      
		<div id="sub_content_in">
			<h1>Resultat des Courses</h1>
			<p>"Usu habeo equidem sanctus no ex melius labitur conceptam eos"</p>
		</div>
	</section>
    <nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand"></a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Rechercher" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Rechercher</button>
    </form>
  </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col mt-3">
            
            <table class="table table-bordered table-inverse table-responsive">
                <thead class="thead-inverse">
                    <tr>
                        <th>Numéro de dossard</th>
                        <th>Nom/Prénom</th>
                        <th>Club</th>
                        <th>Course</th>
                        <th>Temps</th>
                        <th>Classement</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td scope="row">1</td>
                        <td>Fatou Niang</td>
                        <td>Dakar université club</td>
                        <td>vitesse</td>
                        <td>10s</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td scope="row">1</td>
                        <td>mamy Niang</td>
                        <td>Dakar université club</td>
                        <td>vitesse</td>
                        <td>10s</td>
                        <td>2</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>